### ISSUE TITLE
Adjust HTML solution rectangles to accommodate Ctrl/Cmd-+/- zoom

### ISSUE THREAD

**Issue by timdan2** [dtann80/ICS499_WordSearch#12]
To do this, I need to save an array in Javascript containing information on each word when creating the solution rectangles so the information is available to the browser.  Then, onresize(), readjust the size of the rectangles.

**Comment by timdan2** [comment]
This works OK in Firefox, but not Chrome.

**Comment by wallgreeens** [comment]
I think I fixed the directory problem.  It works on my computer.  Could you
delete your wordsearch directory folder and try running the program and
saving a couple times to verify it's working for you as well?

**Comment by timdan2** [comment]
Fixed this.  The Javascript now checks to see what browser is being used; then, adjusts solution rectangles differently for Chrome.

**Comment by timdan2** [comment]
[4] Regression: In Telugu, HTML is showing up as 
expected. However, when I minimize / maximize the 
screens, the solution rectangles are going out of 
position. I think you fixed it in iteration 2 and it is 
a regression. This should be fixed.
Also, when I do Ctrl +, the solution is switching up ( 
out of position) to the first grid. Please try this in 
TELUGU setting.
The above is partially addressed. When I do Ctrl + to increase the font, and then move the vertical scroll bar up and down, the solution rectangles are disappearing or going out of place.
