### ISSUE TITLE
Game Panel

### ISSUE THREAD

**Issue by dtann80** [dtann80/ICS499_WordSearch#22]
New tab with JTable of the saved games with options to open game and build HTML.

**Comment by timdan2** [comment]
Program now loads and displays saved puzzles in Game panel; if the file doesn't exist, program messages: "There are no saved puzzles."

**Comment by wallgreeens** [comment]
Thank you Tim.  I couldn't figure that out. I was going to go to the tutor
for help on tuesday.  the panel still wouldn't load so I made a small
change and now it works on my computer.  Thanks again Tim.
