### ISSUE TITLE
Saving the Puzzle

### ISSUE THREAD

**Issue by timdan2** [dtann80/ICS499_WordSearch#3]
Puzzles shall be saved in a textfile; Each puzzle should carry ID; word list and grid data. Whether NEW file or APPENDED file is decided by configuration.

**Comment by wallgreeens** [comment]
I'll start on this 6-26 just in case I run into trouble I can ask for backup with plenty of time before class.

**Comment by wallgreeens** [comment]
This seems to be working properly now.  Issue is closed.
